# Generated by Django 5.1.1 on 2025-06-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_is_register_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("vendedor", "Vendedor")],
                default="vendedor",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
