# Generated by Django 5.1.1 on 2025-07-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "cuit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="CUIT"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Persona de contacto",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="Número de Factura"),
                ),
                ("invoice_date", models.DateField(verbose_name="Fecha de Factura")),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Total"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Pago Parcial"),
                            ("paid", "Pagado"),
                            ("overdue", "Vencido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de Pago",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="suppliers.supplier",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de Proveedor",
                "verbose_name_plural": "Facturas de Proveedores",
                "ordering": ["-invoice_date"],
                "unique_together": {("supplier", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Fecha de Pago")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("check", "Cheque"),
                            ("card", "Tarjeta"),
                            ("other", "Otro"),
                        ],
                        default="transfer",
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="suppliers.supplierinvoice",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago a Proveedor",
                "verbose_name_plural": "Pagos a Proveedores",
                "ordering": ["-payment_date"],
            },
        ),
    ]
