version: "3"

services:
  web:
    build:
      context: .
    # image:
    command: gunicorn --bind 0.0.0.0:8000 --pythonpath code django_base.wsgi:application --workers=4
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    networks:
      - django-network

networks:
  django-network:
volumes:
  media_volume:
  static_volume:

