# Generated by Django 5.1.1 on 2025-07-23 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Color en formato hexadecimal",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Gasto",
                "verbose_name_plural": "Categorías de Gastos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Gasto"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                            ("biannual", "Semestral"),
                            ("annual", "Anual"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Frecuencia",
                    ),
                ),
                (
                    "due_day",
                    models.IntegerField(
                        help_text="Día del mes en que vence",
                        verbose_name="Día de Vencimiento",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="expenses.expensecategory",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Fijo",
                "verbose_name_plural": "Gastos Fijos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(verbose_name="Año")),
                ("month", models.IntegerField(verbose_name="Mes")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("partial", "Pago Parcial"),
                            ("paid", "Pagado"),
                            ("overdue", "Vencido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de Pago",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pagado")),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "fixed_expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_expenses",
                        to="expenses.fixedexpense",
                        verbose_name="Gasto Fijo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Mensual",
                "verbose_name_plural": "Gastos Mensuales",
                "ordering": ["-year", "-month"],
                "unique_together": {("fixed_expense", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="ExpensePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Fecha de Pago")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("check", "Cheque"),
                            ("card", "Tarjeta"),
                            ("automatic", "Débito Automático"),
                            ("other", "Otro"),
                        ],
                        default="transfer",
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "monthly_expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="expenses.monthlyexpense",
                        verbose_name="Gasto Mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Gasto",
                "verbose_name_plural": "Pagos de Gastos",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="VariableExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre del Gasto"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Fecha del Gasto")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pendiente"), ("paid", "Pagado")],
                        default="pending",
                        max_length=20,
                        verbose_name="Estado de Pago",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Efectivo"),
                            ("transfer", "Transferencia"),
                            ("check", "Cheque"),
                            ("card", "Tarjeta"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Método de Pago",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_expenses",
                        to="expenses.expensecategory",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Variable",
                "verbose_name_plural": "Gastos Variables",
                "ordering": ["-expense_date"],
            },
        ),
    ]
