# Generated by Django 5.1.1 on 2025-09-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlyexpense",
            unique_together=set(),
        ),
    ]
