# Generated by Django 5.1.1 on 2025-09-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_remove_unique_together_monthly_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixedexpense",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Semanal"),
                    ("monthly", "Mensual"),
                    ("quarterly", "Trimestral"),
                    ("biannual", "Semestral"),
                    ("annual", "Anual"),
                ],
                default="monthly",
                max_length=20,
                verbose_name="Frecuencia",
            ),
        ),
    ]
