# Generated by Django 5.1.1 on 2025-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashbox",
            name="closing_notes",
            field=models.TextField(blank=True, null=True, verbose_name="Closing Notes"),
        ),
    ]
