# Generated by Django 5.1.1 on 2025-06-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AddField(
            model_name="sale",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="sale",
            name="ticket_number",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="Ticket Number"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Subtotal"
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_final",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Final"
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Subtotal"
            ),
        ),
    ]
