# Generated by Django 5.1.1 on 2025-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_is_active_sale_notes_sale_ticket_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Unit Price",
            ),
        ),
    ]
