# Generated by Django 5.1.1 on 2025-07-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_saleitem_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("efectivo", "Cash"),
                    ("transferencia", "Transfer"),
                    ("debito", "Debit Card"),
                    ("credito", "Credit Card"),
                    ("qr", "QR"),
                ],
                max_length=20,
                verbose_name="Payment Method",
            ),
        ),
    ]
