# Generated by Django 5.1.1 on 2025-07-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="sale_discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Sale Discount Percentage",
            ),
        ),
    ]
