# Generated by Django 5.1.1 on 2025-06-19 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_cost_price_product_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
